/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.CardLayout;

/**
 *
 * @author ariva
 */
public class Penampil_Gambar_Button extends javax.swing.JFrame {

    /**
     * Creates new form Penampil_Gambar_Button
     */
    public Penampil_Gambar_Button() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jualBT = new javax.swing.JButton();
        beastBT = new javax.swing.JButton();
        apiBT = new javax.swing.JButton();
        exitBT = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 50));

        jualBT.setText("Jualan");
        jualBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jualBTActionPerformed(evt);
            }
        });
        jPanel1.add(jualBT);

        beastBT.setText("Beastar");
        beastBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beastBTActionPerformed(evt);
            }
        });
        jPanel1.add(beastBT);

        apiBT.setText("Api Unggun");
        apiBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apiBTActionPerformed(evt);
            }
        });
        jPanel1.add(apiBT);

        exitBT.setText("Exit");
        exitBT.setPreferredSize(new java.awt.Dimension(50, 23));
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });
        jPanel1.add(exitBT);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Materi Kuliah\\S5\\Pemrograman Berbasis Objek 2\\Aplikasi_Penampil_Gambar\\src\\main\\java\\assets\\jualan.jpeg"));
        imagePanel.add(jLabel1, "0");

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Materi Kuliah\\S5\\Pemrograman Berbasis Objek 2\\Aplikasi_Penampil_Gambar\\src\\main\\java\\assets\\Beastars.jpeg"));
        imagePanel.add(jLabel2, "1");

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Materi Kuliah\\S5\\Pemrograman Berbasis Objek 2\\Aplikasi_Penampil_Gambar\\src\\main\\java\\assets\\api unggun.jpeg"));
        imagePanel.add(jLabel3, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jualBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jualBTActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_jualBTActionPerformed

    private void beastBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beastBTActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_beastBTActionPerformed

    private void apiBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apiBTActionPerformed
        CardLayout cl = (CardLayout) (imagePanel.getLayout());
        cl.show(imagePanel, "2");
    }//GEN-LAST:event_apiBTActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penampil_Gambar_Button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penampil_Gambar_Button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penampil_Gambar_Button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penampil_Gambar_Button.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penampil_Gambar_Button().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apiBT;
    private javax.swing.JButton beastBT;
    private javax.swing.JButton exitBT;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jualBT;
    // End of variables declaration//GEN-END:variables
}
